repos:
  - repo: local
    hooks:
      - id: ktlint-format
        name: ktlint format
        language: system
        entry: bash -c 'mvn -f pulse-app/pom.xml ktlint:format -q --batch-mode'
        pass_filenames: false
        files: \.kt$
