apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - submitter/serviceaccount.yml
  - submitter/deployment.yml
  - submitter/service.yml
  - submitter/backendconfig.yml
  - submitter/pdb.yml
  - processor/serviceaccount.yml
  - processor/deployment.yml
  - processor/pdb.yml
  - projector/serviceaccount.yml
  - projector/deployment.yml
  - projector/service.yml
  - projector/backendconfig.yml
  - projector/pdb.yml
  - otel-collector/serviceaccount.yml
  - otel-collector/clusterrole.yml
  - otel-collector/clusterrolebinding.yml
  - otel-collector/configmap.yml
  - otel-collector/daemonset.yml
  - otel-collector/service.yml
