apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector
  namespace: pulse
  annotations:
    # terraform output: otel_collector_gsa_email
    iam.gke.io/gcp-service-account: OTEL_COLLECTOR_GSA_EMAIL
